#mail
mail :
    host : smtp.gmail.com
    port : 587
    protocol : smtp
    default-encoding : UTF-8
    username : sypioneerdev@gmail.com
    password : tjddydwozl12
    smtp :
        start-tls-enable : true
        auth : true

#url-pattern
spring:
    view:
        prefix: /WEB-INF/pages/
        suffix: .jsp